name: linear_memory
version: 1.0.1
description: Efficiently manages distribution of linear memory. Useful for compilers, etc.
author: Tobe O <thosakwe@gmail.com>
homepage: https://github.com/thosakwe/linear_memory
environment:
  sdk: ">=1.19.0"
dev_dependencies:
  test: ^0.12.0